import { createPlatformNotificationOnce } from "./repositories/notificationRepository.js";

const CONTENT_NOTIFICATIONS = [
  {
    dedupeKey: "release:v2.25.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.25.1",
    body: "El modo dual mejora en escritorio con fullscreen ordenado, atajos de teclado y dimensiones protegidas para Twitch desde 1024 px.",
    href: "/changelog",
    icon: "Activity",
    audience: "all",
    metadata: { source: "release", version: "v2.25.1" },
  },
  {
    dedupeKey: "release:v2.25.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.25.0",
    body: "El modo dual mejora en teléfonos con fullscreen, player 16:9, chat adaptable y una distribución más útil mientras el teclado está abierto.",
    href: "/changelog",
    icon: "Tv",
    audience: "all",
    metadata: { source: "release", version: "v2.25.0" },
  },
  {
    dedupeKey: "release:v2.24.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.24.0",
    body: "El modo dual mejora su fullscreen, distribución móvil y tablet, intercambio de players, audio de Twitch y uso del chat con el teclado abierto.",
    href: "/changelog",
    icon: "Tv",
    audience: "all",
    metadata: { source: "release", version: "v2.24.0" },
  },
  {
    dedupeKey: "release:v2.23.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.23.0",
    body: "El modo dual VK + Twitch estrena una página aislada y cacheable, preparada para mantener el directo disponible durante picos de audiencia.",
    href: "/changelog",
    icon: "PlayCircle",
    audience: "all",
    metadata: { source: "release", version: "v2.23.0" },
  },
  {
    dedupeKey: "release:v2.22.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.22.1",
    body: "Lolweapon mejora la estabilidad durante los directos y reduce consultas, reconexiones y trabajo repetido para soportar mejor los picos de audiencia.",
    href: "/changelog",
    icon: "Activity",
    audience: "all",
    metadata: { source: "release", version: "v2.22.1" },
  },
  {
    dedupeKey: "release:v2.22.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.22.0",
    body: "El Rastreador ahora sincroniza con tu cuenta dónde quedaste viendo cada directo, disponible también en Lolweapon+.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.22.0" },
  },
  {
    dedupeKey: "release:v2.21.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.21.0",
    body: "Lolweapon+ suma notificaciones push y continuar viendo sincronizado entre dispositivos. Sigue en desarrollo, todavía no está disponible para descargar.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.21.0" },
  },
  {
    dedupeKey: "release:v2.20.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.20.0",
    body: "Empezamos a construir Lolweapon+, la futura app móvil: esta versión suma la autenticación necesaria para iniciar sesión con tu cuenta cuando esté disponible. Todavía está en desarrollo.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.20.0" },
  },
  {
    dedupeKey: "release:v2.19.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.19.1",
    body: "La plataforma refuerza la seguridad de sesiones e inicios de sesión, reduce la retención de datos técnicos y mantiene el acceso con Twitch y contraseña.",
    href: "/changelog",
    icon: "ShieldCheck",
    audience: "all",
    metadata: { source: "release", version: "v2.19.1" },
  },
  {
    dedupeKey: "release:v2.19.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.19.0",
    body: "Piero mejora su experiencia móvil, controles, subtítulos y reproducción remota; el modo dual VK + Twitch también gana compatibilidad en Android y iOS.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.19.0" },
  },
  {
    dedupeKey: "release:v2.18.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.18.0",
    body: "Piero estrena controles renovados, continuación entre partes, Google Cast y subtítulos personalizables; Openings/Endings evita duplicados en altas manuales.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.18.0" },
  },
  {
    dedupeKey: "release:v2.17.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.17.0",
    body: "Administración estrena Audiencia web para revisar presencia concurrente, evolución por minuto y comparaciones históricas por directo, con referencia separada de Twitch.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.17.0" },
  },
  {
    dedupeKey: "release:v2.16.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.16.1",
    body: "Inicio corrige su contador propio para mostrar quién está presente ahora, sin acumular conexiones de personas que ya abandonaron la página.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.16.1" },
  },
  {
    dedupeKey: "release:v2.16.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.16.0",
    body: "Inicio mejora sus modos Twitch y VK + Twitch, suma suscripciones y presencia propia; Piero incorpora subtítulos y reproducción remota compatible.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.16.0" },
  },
  {
    dedupeKey: "release:v2.15.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.15.0",
    body: "Inicio estrena el modo dual VK + Twitch, teatro con chat y presencia en tiempo real; los resubidos de Piero suman un reproductor con progreso, atajos, PiP y pantalla completa.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.15.0" },
  },
  {
    dedupeKey: "release:v2.14.2",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.14.2",
    body: "El Tier List estrena modo Usuario/Administración y homologa sus filtros de Ocultar/Ver con el Calendario de temporada, que también los suma.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.14.2" },
  },
  {
    dedupeKey: "release:v2.14.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.14.1",
    body: "Openings/Endings admite varias fuentes de video por tema, con pestañas dinámicas en el reproductor, y se corrige que cambiar entre Openings y Endings reiniciara la temporada seleccionada.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.14.1" },
  },
  {
    dedupeKey: "release:v2.14.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.14.0",
    body: "Biblioteca de anime estrena el Tier List de Animes y de Openings/Endings: arrastra, arma tus filas, comparte tu tablero con un link público y guárdalo automáticamente con sesión iniciada.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.14.0" },
  },
  {
    dedupeKey: "release:v2.13.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.13.0",
    body: "Biblioteca de anime estrena el Calendario de temporada: emisiones semanales, plataformas de streaming, favoritos y un modal de detalle con trailer y sinopsis.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.13.0" },
  },
  {
    dedupeKey: "release:v2.12.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.12.1",
    body: "La plataforma mejora sus mantenedores, modales y notificaciones con una experiencia más clara, consistente y cómoda, junto con correcciones en Twitch EventSub.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.12.1" },
  },
  {
    dedupeKey: "release:v2.12.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.12.0",
    body: "El Rastreador estrena filtros de enlaces y un flujo seguro para exportar, revisar e importar actualizaciones mediante Excel.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.12.0" },
  },
  {
    dedupeKey: "release:v2.11.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.11.0",
    body: "Sugerencias/Reclamos estrena tickets con conversación, notificaciones y mantenedor administrativo en tiempo real.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.11.0" },
  },
  {
    dedupeKey: "release:v2.10.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.10.0",
    body: "RTFM reúne las fuentes del archivo y suma un mapa de navegación con roles, permisos y accesos por pantalla.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.10.0" },
  },
  {
    dedupeKey: "release:v2.9.1",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.9.1",
    body: "El perfil recupera el menú lateral completo y aclara el alcance actual de los beneficios automáticos.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.9.1" },
  },
  {
    dedupeKey: "release:v2.9.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.9.0",
    body: "Ya puedes iniciar sesión o registrarte con Google / YouTube y conectar varios métodos de acceso a una misma cuenta.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.9.0" },
  },
  {
    dedupeKey: "release:v2.8.0",
    type: "activity",
    source: "content",
    severity: "success",
    title: "Nueva versión v2.8.0",
    body: "Estrenamos el centro completo de notificaciones, avisos programados y sesión compartida entre Resubidos y Viendo.",
    href: "/changelog",
    icon: "Sparkles",
    audience: "all",
    metadata: { source: "release", version: "v2.8.0" },
  },
];

export async function syncContentNotifications() {
  let synced = 0;

  for (const notification of CONTENT_NOTIFICATIONS) {
    const result = await createPlatformNotificationOnce(notification);

    if (result) {
      synced += 1;
    }
  }

  return { total: CONTENT_NOTIFICATIONS.length, synced };
}
