export const newsGuideBenefits = [
  {
    key: "guest",
    audience: "Invitado",
    accent: "cyan",
    icon: "Compass",
    featured: true,
    title: "Explora antes de crear cuenta",
    description: "Puedes revisar el archivo, ver resubidos, entrar a la biblioteca de anime y conocer las novedades. SpaceDrum queda reservado para usuarios con beneficio activo.",
    items: [
      "Explorar directos, anime y novedades.",
      "Ver fichas y enlaces disponibles.",
      "Inicia sesión para guardar listas, progreso y puntuaciones.",
    ],
    cta: { label: "Explorar rastreador", href: "/rastreador" },
  },
  {
    key: "registered",
    audience: "Registrado",
    accent: "purple",
    icon: "BookmarkCheck",
    featured: true,
    title: "Guarda tu avance personal",
    description: "Al iniciar sesión la plataforma recuerda tus marcas, listas, datos de perfil y progreso de lectura cuando tengas un beneficio activo.",
    items: [
      "Guardar directos y marcarlos como vistos.",
      "Usar Mi lista y Mi lista anime.",
      "Guardar avatar, perfil, chulopuntos y progreso cuando tu acceso lo permita.",
    ],
    cta: { label: "Ir a mi lista", href: "/mi-lista", authOnly: true },
  },
  {
    key: "community",
    audience: "Comunidad Twitch / YouTube",
    accent: "green",
    icon: "BadgeCheck",
    title: "Beneficios conectados a la comunidad",
    description: "Si conectas Twitch o, a futuro, YouTube, el sistema puede reconocer beneficios activos del canal y asignar accesos cuando correspondan. También puedes usar registro manual si no quieres conectar una cuenta externa.",
    items: [
      "Rol automático por Tier, VIP o moderador en Twitch.",
      "Acceso configurable por pantalla y acción.",
      "Lecturas como SpaceDrum para suscriptores o miembros con beneficio activo.",
    ],
    cta: { label: "Iniciar sesión", href: "/login" },
  },
  {
    key: "moderator",
    audience: "Moderador",
    accent: "orange",
    icon: "ShieldCheck",
    title: "Ayuda sin exponer todo",
    description: "Los moderadores pueden apoyar tareas específicas cuando el rol tenga permisos, sin depender de formularios completos o accesos globales.",
    items: [
      "Usar formularios compactos si el rol lo permite.",
      "Editar contenido acotado por pantalla.",
      "Operar con trazabilidad en auditoría.",
    ],
    cta: { label: "Ver herramientas disponibles", href: "/administracion/roles", adminOnly: true },
  },
  {
    key: "admin",
    audience: "Admin / Dios",
    accent: "pink",
    icon: "UserRoundCog",
    title: "Administra la plataforma",
    description: "Los perfiles administrativos mantienen usuarios, roles, contenido y configuraciones con historial de acciones.",
    items: [
      "Administrar usuarios, roles y permisos.",
      "Mantener rastreador, anime, tags y SpaceDrum.",
      "Revisar historial y snapshots de cambios.",
    ],
    cta: { label: "Ir a administración", href: "/administracion/usuarios", adminOnly: true },
  },
];

export const newsGuideUpdates = [
  {
    type: "Mejora",
    audience: "Todos",
    module: "Rastreador",
    date: "v2.4.2",
    icon: "Download",
    title: "Ayuda para descargar resubidos",
    description: "El detalle de cada resubido suma opciones guiadas para usar Cobalt o Streamlink cuando el player de OK.RU no carga.",
    href: "/rastreador",
    cta: "Ver rastreador",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.4.0",
    icon: "Compass",
    title: "Menú lateral en árbol",
    description: "La navegación agrupa Archivo VOD, Biblioteca de anime, Lecturas y Administración en nodos desplegables para ocupar menos espacio.",
    href: "/inicio",
    cta: "Ver navegación",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Rastreador",
    date: "v2.4.0",
    icon: "History",
    title: "Nuevos modos de vista",
    description: "El rastreador y la biblioteca de anime incorporan vistas Cómodo, Compacto y Tabla para elegir entre cards visuales y listados densos.",
    href: "/rastreador",
    cta: "Probar vistas",
  },
  {
    type: "Mejora",
    audience: "Usuarios",
    module: "Anime",
    date: "v2.4.0",
    icon: "Star",
    title: "Cards compactas de anime",
    description: "El modo compacto de anime ahora muestra poster, progreso, nota destacada, favoritos, nota personal y acceso a resubidos en menos espacio.",
    href: "/biblioteca-anime/viendo",
    cta: "Ver anime",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.3.0",
    icon: "Sparkles",
    title: "Novedades y guía de uso",
    description: "Nueva página para entender qué puedes hacer como invitado, usuario registrado, comunidad Twitch/YouTube o perfil administrativo.",
    href: "/novedades",
    cta: "Ver guía",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.3.0",
    icon: "History",
    title: "Historial de cambios completo",
    description: "El changelog ahora vive en su propia página, con filtros por texto, módulo y tipo para revisar toda la evolución de la plataforma.",
    href: "/changelog",
    cta: "Ver historial",
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Anime",
    date: "v2.2",
    icon: "Star",
    title: "Chulopuntos para calificar anime",
    description: "Las páginas Viendo y Terminados ahora permiten puntuar anime con notas decimales y mostrar la nota destacada por Kala.",
    href: "/biblioteca-anime/viendo",
    cta: "Ver anime",
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Rastreador",
    date: "v2.2",
    icon: "BookmarkCheck",
    title: "Mi lista de directos",
    description: "Guarda directos, marca vistos y separa lo pendiente de lo ya revisado desde una página personal.",
    href: "/mi-lista",
    cta: "Ver mi lista",
    authOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Anime",
    date: "v2.2",
    icon: "BookOpenCheck",
    title: "Mi lista anime",
    description: "Centraliza favoritos, viendo, terminados y pendientes para llevar tu seguimiento personal de anime.",
    href: "/mi-lista/anime",
    cta: "Ver lista anime",
    authOnly: true,
  },
  {
    type: "Mejora",
    audience: "Twitch / YouTube",
    module: "SpaceDrum",
    date: "v2.2",
    icon: "BookOpenCheck",
    title: "Lector bilingüe con progreso",
    description: "SpaceDrum permite leer capítulos en español e inglés, guardar progreso y continuar lectura. Por ahora se desbloquea con suscripción activa en Twitch o membresía de YouTube, además de roles administrativos.",
    href: "/spacedrum",
    cta: "Leer SpaceDrum",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "spacedrum.view",
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Perfil",
    date: "v2.1",
    icon: "UserRoundCog",
    title: "Perfil configurable",
    description: "Los usuarios pueden actualizar alias, email, avatar local y contraseña desde Configurar perfil.",
    href: "/perfil",
    cta: "Configurar perfil",
    authOnly: true,
  },
  {
    type: "Mejora",
    audience: "Admin",
    module: "Administración",
    date: "v2.1",
    icon: "History",
    title: "Historial administrativo",
    description: "Los mantenedores registran quién hizo cada acción, cuándo, sobre qué módulo y con snapshots de cambios.",
    href: "/administracion/roles",
    cta: "Ver administración",
    adminOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Admin",
    module: "Administración",
    date: "v2.1",
    icon: "ShieldCheck",
    title: "Mantenedores y permisos",
    description: "Usuarios, roles, rastreador, tags, anime y SpaceDrum se administran desde módulos separados y auditables.",
    href: "/administracion/usuarios",
    cta: "Ver mantenedores",
    adminOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Login",
    date: "v2.0",
    icon: "LogIn",
    title: "Login manual y Twitch",
    description: "La plataforma permite usuarios manuales, registro local y conexión con Twitch para sincronizar roles.",
    href: "/perfil",
    cta: "Configurar perfil",
    authOnly: true,
    loginLabel: "Iniciar sesión",
  },
];

export const newsGuideTutorials = [
  {
    module: "Rastreador",
    href: "/rastreador",
    cta: "Abrir rastreador",
    steps: ["Busca por título, tag o descripción.", "Filtra por año, mes, estado y tags.", "Abre la ficha para ver resubidos."],
  },
  {
    module: "Mi lista",
    href: "/mi-lista",
    cta: "Ver mi lista",
    authOnly: true,
    steps: ["Guarda directos desde el rastreador.", "Separa guardados, por ver y vistos.", "Continúa desde tu lista personal."],
  },
  {
    module: "Biblioteca de anime",
    href: "/biblioteca-anime/viendo",
    cta: "Abrir biblioteca",
    steps: ["Marca Favorito, Quiero ver, Viendo o Terminado.", "Califica con chulopuntos si tu rol lo permite.", "Abre resubidos asociados."],
  },
  {
    module: "SpaceDrum",
    href: "/spacedrum",
    cta: "Leer SpaceDrum",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "spacedrum.view",
    steps: ["Activa una suscripción de Twitch o membresía de YouTube.", "Inicia sesión para sincronizar tu acceso.", "Selecciona idioma y continúa tu lectura."],
  },
  {
    module: "Perfil",
    href: "/perfil",
    cta: "Configurar perfil",
    authOnly: true,
    steps: ["Actualiza alias y email.", "Sube o quita avatar.", "Cambia contraseña cuando corresponda."],
  },
  {
    module: "Administración",
    href: "/administracion/roles",
    cta: "Ir a administración",
    adminOnly: true,
    steps: ["Gestiona mantenedores según permisos.", "Configura roles por pantalla.", "Revisa historial y auditoría."],
  },
];

export const newsGuideHowTo = [
  {
    title: "Opciones para descargar",
    icon: "Download",
    steps: ["Abre la ficha del resubido.", "Presiona Opciones para descargar.", "Usa Cobalt o Streamlink si OK.RU falla."],
  },
  {
    title: "Guardar un directo",
    icon: "BookmarkCheck",
    steps: ["Entra al rastreador.", "Presiona Guardar en el directo.", "Revísalo luego desde Mi lista."],
  },
  {
    title: "Marcar como visto",
    icon: "Check",
    steps: ["Busca el directo.", "Presiona Visto.", "Filtra tu lista para separar pendientes."],
  },
  {
    title: "Calificar un anime",
    icon: "Star",
    steps: ["Abre Viendo o Terminados.", "Presiona Puntuar o Tu nota.", "Guarda una nota entre 1 y 8."],
  },
  {
    title: "Continuar SpaceDrum",
    icon: "BookOpenCheck",
    steps: ["Activa una suscripción de Twitch o membresía de YouTube.", "Inicia sesión para sincronizar tu acceso.", "Presiona Continuar lectura para guardar el avance."],
  },
  {
    title: "Cambiar avatar",
    icon: "UserRoundCog",
    steps: ["Abre Configurar perfil.", "Arrastra o selecciona imagen.", "Guarda los cambios."],
  },
  {
    title: "Conectar Twitch",
    icon: "BadgeCheck",
    steps: ["Abre Login.", "Elige Twitch.", "Autoriza para sincronizar tu cuenta."],
  },
];

export const newsGuideComparison = [
  { feature: "Ver archivo y resubidos", guest: true, registered: true },
  { feature: "Guardar directos", guest: false, registered: true },
  { feature: "Marcar visto", guest: false, registered: true },
  { feature: "Mi lista", guest: false, registered: true },
  { feature: "Mi lista anime", guest: false, registered: true },
  { feature: "Progreso SpaceDrum", guest: false, registered: "Con acceso" },
  { feature: "Perfil y avatar", guest: false, registered: true },
  { feature: "Calificar anime", guest: false, registered: true },
  { feature: "Beneficios por rol", guest: false, registered: "Según rol" },
];

export const newsGuideChangelog = [
  {
    version: "v2.4.2",
    date: "16 jun 2026",
    title: "Opciones de descarga para resubidos",
    type: "Mejora",
    modules: ["Rastreador"],
    changes: [
      "El detalle de resubido incorpora un modal de opciones para descargar cuando el player de OK.RU falla.",
      "El método recomendado copia el link de OK.RU y abre Cobalt para que el usuario intente descargar desde su navegador.",
      "El método avanzado con Streamlink mantiene instrucciones detalladas por sistema operativo, comando listo para copiar y ayuda de problemas comunes.",
      "La descarga no pasa por el servidor de la plataforma y no agrega integración API ni costos de proxy.",
    ],
  },
  {
    version: "v2.4.1",
    date: "15 jun 2026",
    title: "Corrección al crear card desde Twitch",
    type: "Corrección",
    modules: ["Rastreador", "Administración"],
    changes: [
      "Crear card desde Twitch ahora actualiza el listado del rastreador inmediatamente sin requerir recargar la página.",
      "El flujo de archivo desde Twitch usa actualización puntual del directo y evita depender de un refresco adicional para mostrar la card.",
    ],
  },
  {
    version: "v2.4.0",
    date: "15 jun 2026",
    title: "Menú árbol y modos compactos",
    type: "Mejora",
    modules: ["Plataforma", "Rastreador", "Anime"],
    changes: [
      "El menú lateral ahora usa una estructura en árbol con nodos desplegables para Archivo VOD, Biblioteca de anime, Lecturas y Administración.",
      "Administración organiza sus secciones internas con subárboles para Biblioteca de anime y SpaceDrum.",
      "El selector de densidad suma la vista Tabla y conserva Cómodo y Compacto para rastreador y biblioteca de anime.",
      "El modo compacto del rastreador usa cards densas con fecha, estado, tags resumidos, disponibilidad y acciones personales.",
      "El modo compacto de anime incorpora cards con poster, progreso, nota destacada, favoritos, nota personal y acceso al resubido.",
      "La vista Tabla queda disponible en pantallas medianas y grandes, con fallback automático a Compacto en mobile.",
      "Pulido visual del menú árbol: padres más sobrios, hijo activo destacado, línea guía e indicadores desplegables más claros.",
    ],
  },
  {
    version: "v2.3.0",
    date: "13 jun 2026",
    title: "Novedades y changelog",
    changes: [
      "Nueva página Novedades con beneficios por tipo de usuario, guías rápidas y accesos según sesión o permisos.",
      "Nueva página Historial de cambios con filtros por texto, módulo y tipo de cambio.",
      "Permisos configurables news.view y changelog.view, asignados por defecto a los roles predefinidos.",
      "El login, registro y Twitch conservan la página de retorno, incluso cuando se navega desde enlaces con ancla.",
      "Los selectores del changelog usan el componente visual estandarizado de la plataforma.",
    ],
  },
  {
    version: "v2.2.1",
    date: "02 jun 2026",
    title: "Ajustes de autenticación y estabilidad",
    changes: [
      "El login manual actualiza correctamente el último acceso del usuario.",
      "Correcciones finales sobre miniaturas y experiencia de SpaceDrum.",
    ],
  },
  {
    version: "v2.2.0",
    date: "30 may 2026",
    title: "SpaceDrum por rol y administración editorial",
    changes: [
      "Página de SpaceDrum con acceso por rol, selector de capítulos, lector, progreso por usuario e idioma.",
      "Mantenedores administrativos para capítulos, páginas, configuración e importación de SpaceDrum.",
      "Importación remota desde la web original, conservando progreso de usuarios registrados.",
      "Submenú administrativo para dividir capítulos, páginas, configuración e importación.",
      "Mejoras responsivas en tablas, acciones de anime y modo de lectura.",
      "Pulido visual de cards, hero, créditos, apoyo al proyecto y lector.",
    ],
  },
  {
    version: "v2.1.1",
    date: "24 may 2026",
    title: "Documentación y auditoría pulida",
    changes: [
      "Documentación del flujo manual de Git, versionado y releases.",
      "Corrección del desborde visual en el modal de historial administrativo.",
    ],
  },
  {
    version: "v2.1.0",
    date: "24 may 2026",
    title: "Chulopuntos, auditoría y mejoras del dashboard",
    changes: [
      "Sistema de chulopuntos con notas personales de 1 a 8 y soporte decimal.",
      "Nota destacada por Kala visible en cards de Viendo y Terminados.",
      "Historial administrativo con usuario, fecha, módulo, registro e instantáneas de cambios.",
      "Mejoras de experiencia en Inicio, player Twitch y convenciones internas del proyecto.",
      "Documentación del proyecto, backlog y guías compartidas para agentes.",
    ],
  },
  {
    version: "v2.0.0",
    date: "17 may 2026",
    title: "Actividad personal, CI/CD y estados de carga",
    changes: [
      "Seguimiento personal de actividad para guardar y marcar contenidos.",
      "Mi lista de directos con estados personales y navegación dedicada.",
      "Mejoras de UX, estados de carga y comportamiento del dashboard.",
      "Workflows de despliegue con respaldos, rollback y generación de Prisma.",
      "Mejor tolerancia ante cambios de navegación y carga inicial.",
    ],
  },
  {
    version: "v1.9.2",
    date: "15 may 2026",
    title: "Formulario compacto de anime",
    changes: [
      "Simplificación del formulario compacto de Biblioteca de anime.",
      "Campos acotados para edición rápida desde Viendo y Terminados.",
    ],
  },
  {
    version: "v1.9.1",
    date: "15 may 2026",
    title: "Acceso Twitch para usuarios nuevos",
    changes: [
      "Corrección para permitir el inicio de sesión de nuevos usuarios Twitch.",
      "Mejor manejo del alta inicial cuando la cuenta todavía no existe en plataforma.",
    ],
  },
  {
    version: "v1.9.0",
    date: "15 may 2026",
    title: "Mantenedores y permisos de plataforma",
    changes: [
      "Mantenedores administrativos para módulos principales de la plataforma.",
      "Permisos configurables por pantalla y acción desde Roles.",
      "Base para administrar usuarios, roles, rastreador, tags y anime con una línea visual común.",
      "Panel administrativo de tags con categorías, reglas, asignación manual y eliminación segura.",
      "Estandarización de tablas con filtros, paginación, ordenamiento, IDs y estados.",
    ],
  },
  {
    version: "v1.8.0",
    date: "14 may 2026",
    title: "Mantenedores de Biblioteca de anime",
    changes: [
      "Administración de anime Viendo y Terminados desde el módulo de administración.",
      "Operaciones internas para estado, eliminación y edición según permisos.",
      "Homologación de tablas, modales, filtros y acciones con Usuarios y Roles.",
      "Búsqueda y precarga desde AniList para crear o editar fichas.",
      "Formularios completo y compacto según permisos del rol.",
    ],
  },
  {
    version: "v1.7.3",
    date: "12 may 2026",
    title: "Entrada de invitados corregida",
    changes: [
      "Cambio del acceso invitado para mostrar Iniciar sesión de forma más clara.",
    ],
  },
  {
    version: "v1.7.2",
    date: "12 may 2026",
    title: "OAuth Twitch multi-host",
    changes: [
      "Soporte para iniciar sesión con Twitch desde distintos hosts configurados.",
      "Corrección del flujo QA/producción cuando se navega desde dominios separados.",
    ],
  },
  {
    version: "v1.7.1",
    date: "12 may 2026",
    title: "Redirección Twitch configurable",
    changes: [
      "Uso del origen configurado para evitar redirecciones erróneas a localhost.",
    ],
  },
  {
    version: "v1.7.0",
    date: "12 may 2026",
    title: "Autenticación, usuarios y roles",
    changes: [
      "Login manual, registro local y login con Twitch.",
      "Módulo de usuarios con restricciones especiales para Dios.",
      "Módulo de roles con permisos configurables por pantalla y acción.",
      "Perfil configurable con alias, email, avatar y cambio de contraseña.",
      "Roles temporales de comunidad, Twitch, YouTube, Público e Invitado.",
      "Reglas de acceso para pantallas públicas y administrativas según permisos.",
    ],
  },
  {
    version: "v1.6.0",
    date: "06 may 2026",
    title: "Persistencia normalizada en Postgres",
    changes: [
      "Migración desde datos JSON hacia modelo normalizado en PostgreSQL.",
      "Importadores y exportadores para directos, anime, tags y configuraciones.",
      "Base para operar local, QA y producción con Prisma y Postgres.",
      "Scripts para resetear secuencias y mantener IDs lógicos en ambientes limpios.",
      "Documentación operativa para migración, backups y restauración.",
    ],
  },
  {
    version: "v1.5.0",
    date: "01 may 2026",
    title: "Biblioteca de anime consolidada",
    changes: [
      "Reemplazo de la vista antigua de Viendo por la Biblioteca de anime.",
      "Sincronización de edición de fichas entre vistas públicas y administrativas iniciales.",
      "Mejoras de mini player y comportamiento del layout general.",
    ],
  },
  {
    version: "v1.4.1",
    date: "01 may 2026",
    title: "Orden y metadata de anime",
    changes: [
      "Mejoras en ordenamiento y presentación de la biblioteca.",
      "Conservación de metadata editada manualmente.",
    ],
  },
  {
    version: "v1.4.0",
    date: "01 may 2026",
    title: "Seguimiento de anime mejorado",
    changes: [
      "Mejoras en fichas de anime y seguimiento de episodios.",
      "Priorización de temporadas completas y capítulos comprados.",
      "Ajustes de títulos y metadata desde AniList.",
      "Cruce entre tags del rastreador y fichas de biblioteca.",
    ],
  },
  {
    version: "v1.3.1",
    date: "01 may 2026",
    title: "Corrección visual del menú anime",
    changes: [
      "Corrección del icono de Biblioteca de anime en el menú.",
    ],
  },
  {
    version: "v1.3.0",
    date: "01 may 2026",
    title: "Biblioteca de anime",
    changes: [
      "Alta del módulo Biblioteca de anime.",
      "Vistas para animes en seguimiento y terminados.",
      "Gestión inicial de fichas conectadas al rastreador y AniList.",
      "Primeras mejoras de orden, filtros y presentación de cards de anime.",
    ],
  },
  {
    version: "v1.2.5",
    date: "29 abr 2026",
    title: "Player Twitch estabilizado",
    changes: [
      "Estabilización de la ubicación del player Twitch en Inicio.",
    ],
  },
  {
    version: "v1.2.4",
    date: "29 abr 2026",
    title: "Tabla de rastreador y controles",
    changes: [
      "Mejoras en la tabla del rastreador.",
      "Controles más claros para abrir resubidos.",
    ],
  },
  {
    version: "v1.2.3",
    date: "28 abr 2026",
    title: "Mini player persistente",
    changes: [
      "Player Twitch persistente al cambiar entre páginas del rastreador.",
      "Menos parpadeos en embeds durante navegación interna.",
    ],
  },
  {
    version: "v1.2.2",
    date: "28 abr 2026",
    title: "Ayuda de descarga con Streamlink",
    changes: [
      "Guía auxiliar para descargar directos con Streamlink.",
    ],
  },
  {
    version: "v1.2.1",
    date: "28 abr 2026",
    title: "Links sociales en sidebar",
    changes: [
      "Accesos sociales movidos al menú lateral.",
      "Branding y favicon incorporados.",
    ],
  },
  {
    version: "v1.2.0",
    date: "27 abr 2026",
    title: "Página de detalle de resubido",
    changes: [
      "Nueva página para ver un resubido con player, metadata, tags y enlaces.",
      "Correcciones de carga al entrar al rastreador desde otras vistas.",
      "Primeras mejoras de embeds Twitch y acciones del archivo.",
      "Prototipo inicial de SpaceDrum dentro de la navegación.",
      "Categorías globales de tags para organizar el rastreador.",
    ],
  },
  {
    version: "v1.1.0",
    date: "26 abr 2026",
    title: "Hub multi-página",
    changes: [
      "Estructura multi-página para Inicio, Twitch y vistas internas.",
      "Primer prototipo de navegación integrada en la plataforma.",
    ],
  },
  {
    version: "v1.0.0",
    date: "19 abr 2026",
    title: "Base inicial en Next.js",
    changes: [
      "Migración inicial de la web de resubidos a Next.js full stack.",
      "Primera base del archivo VOD y navegación de la plataforma.",
    ],
  },
];
