export const newsGuideBenefits = [
  {
    key: "guest",
    audience: "Invitado",
    accent: "cyan",
    icon: "Compass",
    featured: true,
    title: "Explora antes de crear cuenta",
    description: "Puedes revisar el archivo, ver resubidos, entrar a la biblioteca de anime y conocer las novedades. SpaceDrum queda reservado para usuarios con beneficio activo.",
    items: [
      "Explorar directos, anime y novedades.",
      "Ver fichas y enlaces disponibles.",
      "Inicia sesión para guardar listas, progreso y puntuaciones.",
    ],
    cta: { label: "Explorar rastreador", href: "/rastreador" },
  },
  {
    key: "registered",
    audience: "Registrado",
    accent: "purple",
    icon: "BookmarkCheck",
    featured: true,
    title: "Guarda tu avance personal",
    description: "Al iniciar sesión la plataforma recuerda tus marcas, listas, datos de perfil y progreso de lectura cuando tengas un beneficio activo.",
    items: [
      "Guardar directos y marcarlos como vistos.",
      "Usar Mi lista y Mi lista anime.",
      "Enviar sugerencias o reclamos y continuar la conversación desde tu bandeja.",
      "Guardar avatar, perfil, chulopuntos y progreso cuando tu acceso lo permita.",
    ],
    cta: { label: "Ir a mi lista", href: "/mi-lista", authOnly: true },
  },
  {
    key: "community",
    audience: "Comunidad Twitch / YouTube",
    accent: "green",
    icon: "BadgeCheck",
    title: "Beneficios conectados a la comunidad",
    description: "Puedes iniciar sesión con Twitch o Google / YouTube, mantener varias formas de acceso en una misma cuenta y conservar un usuario manual si prefieres entrar con contraseña.",
    items: [
      "Beneficios adicionales solo para suscripciones pagadas de Twitch.",
      "Google / YouTube como método de registro e inicio de sesión.",
      "Acceso configurable por pantalla y acción.",
      "Los roles TW_VIP y YT_Miembro no se pueden obtener ni entregar beneficios adicionales hasta que Kala autorice su activación.",
    ],
    cta: { label: "Iniciar sesión", href: "/login" },
  },
  {
    key: "moderator",
    audience: "Moderador",
    accent: "orange",
    icon: "ShieldCheck",
    title: "Ayuda sin exponer todo",
    description: "Los moderadores pueden apoyar tareas específicas cuando el rol tenga permisos, sin depender de formularios completos o accesos globales.",
    items: [
      "Usar formularios compactos si el rol lo permite.",
      "Editar contenido acotado por pantalla.",
      "Operar con trazabilidad en auditoría.",
    ],
    cta: { label: "Ver herramientas disponibles", href: "/administracion/roles", adminOnly: true },
  },
  {
    key: "admin",
    audience: "Admin / Dios",
    accent: "pink",
    icon: "UserRoundCog",
    title: "Administra la plataforma",
    description: "Los perfiles administrativos mantienen usuarios, roles, contenido y configuraciones con historial de acciones.",
    items: [
      "Administrar usuarios, roles y permisos.",
      "Responder tickets de soporte y cambiar su estado.",
      "Mantener rastreador, anime, tags y SpaceDrum.",
      "Revisar historial y snapshots de cambios.",
    ],
    cta: { label: "Ir a administración", href: "/administracion/usuarios", adminOnly: true },
  },
];

export const newsGuideUpdates = [
  {
    type: "Nuevo",
    audience: "Administración",
    module: "Rastreador / Excel",
    date: "v2.12.0",
    icon: "FileSpreadsheet",
    title: "Edición masiva del rastreador con Excel",
    description: "El mantenedor del Rastreador ahora permite localizar enlaces OKRU o Telegram faltantes y duplicados, exportar exactamente los registros filtrados y volver a importar el mismo archivo para revisar y aplicar actualizaciones masivas de forma controlada.",
    href: "/administracion/rastreador",
    cta: "Abrir mantenedor",
    adminOnly: true,
  },
  {
    type: "Mejora",
    audience: "Administración",
    module: "Plataforma / Datos",
    date: "v2.12.0",
    icon: "ShieldCheck",
    title: "Operaciones masivas y respaldos más seguros",
    description: "La importación valida identificadores, conflictos y cambios antes de confirmar. Además, los respaldos y restauraciones PostgreSQL detectan el entorno disponible y las sesiones antiguas se limpian automáticamente después de restaurar una base de datos.",
    href: "/changelog",
    cta: "Ver detalles",
    adminOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Soporte / Administración",
    date: "v2.11.0",
    icon: "MessageCircle",
    title: "Sugerencias/Reclamos con tickets",
    description: "Los usuarios registrados pueden crear sugerencias o reclamos, seguirlos como conversación y recibir respuestas por la campana. Administración suma un mantenedor de tickets con filtros, estados, chat y actualizaciones en tiempo real.",
    href: "/sugerencias-reclamos",
    cta: "Abrir soporte",
    authOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "RTFM / Navegación",
    date: "v2.10.0",
    icon: "Compass",
    title: "RTFM y mapa de accesos",
    description: "Se agrega una pantalla RTFM con las fuentes principales del archivo, notas comunitarias, playlists de OKRU y un mapa de navegación que explica qué roles pueden entrar a cada pantalla.",
    href: "/rtfm",
    cta: "Leer RTFM",
  },
  {
    type: "Mejora",
    audience: "Todos",
    module: "Login / Perfil",
    date: "v2.9.1",
    icon: "Sparkles",
    title: "Perfil y beneficios más claros",
    description: "El perfil vuelve a usar el menú lateral completo y ahora muestra con más claridad que, por ahora, los beneficios automáticos solo consideran suscripciones pagadas de Twitch.",
    href: "/perfil",
    cta: "Revisar perfil",
    loginLabel: "Iniciar sesión",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Login / Perfil",
    date: "v2.9.0",
    icon: "BadgeCheck",
    title: "Inicio de sesión con Google / YouTube",
    description: "Ahora puedes crear cuenta o iniciar sesión con Google / YouTube, conectar varias formas de acceso a la misma cuenta y completar tu perfil con usuario, alias y contraseña opcional. Por ahora, los beneficios automáticos solo consideran suscripciones pagadas de Twitch.",
    href: "/perfil",
    cta: "Configurar cuenta",
    loginLabel: "Iniciar sesión",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Notificaciones / Plataforma",
    date: "v2.8.0",
    icon: "BellRing",
    title: "Centro de notificaciones completo",
    description: "La campana ahora se complementa con una bandeja completa para buscar y administrar avisos. La plataforma incorpora notificaciones programadas, permisos separados, una experiencia móvil renovada y sesión compartida entre los dominios de Resubidos y Viendo.",
    href: "/changelog",
    cta: "Ver cambios",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Rastreador / Notificaciones",
    date: "v2.7.0",
    icon: "BellRing",
    title: "Avisos de nuevos resubidos",
    description: "El equipo ahora puede avisar cuando un resubido está disponible. La notificación llega en tiempo real, abre directamente la ficha del directo y mantiene confirmación e historial para evitar envíos accidentales.",
    href: "/rastreador",
    cta: "Ver rastreador",
  },
  {
    type: "Mejora",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.6.2",
    icon: "Tv",
    title: "Mini player más fluido y correcto",
    description: "El mini player ya no aparece en el inicio, el stream vuelve a mostrarse integrado en la página principal y el redimensionado es completamente fluido sin desfase entre el frame y los botones.",
    href: "/inicio",
    cta: "Ir al inicio",
  },
  {
    type: "Corrección",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.6.1",
    icon: "Check",
    title: "Ajustes en notificaciones y player",
    description: "Las notificaciones de directos en vivo vía Twitch EventSub quedan activas. El mini player ahora se muestra correctamente al navegar a Novedades e Historial de cambios.",
    href: "/inicio",
    cta: "Ir al inicio",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.6.0",
    icon: "BellRing",
    title: "Centro de notificaciones",
    description: "La campana de la barra superior avisa directos en vivo, nuevos videos de YouTube y novedades de la plataforma en tiempo real. Los usuarios invitados también reciben alertas públicas.",
    href: "/inicio",
    cta: "Ir al inicio",
  },
  {
    type: "Corrección",
    audience: "Todos",
    module: "Rastreador / Anime",
    date: "v2.5.2",
    icon: "Check",
    title: "Ajustes visuales en listas",
    description: "El rastreador y la biblioteca de anime reciben pulidos en estados personales, botones de acción y carga incremental al navegar entre pantallas.",
    href: "/rastreador",
    cta: "Ver rastreador",
  },
  {
    type: "Mejora",
    audience: "Twitch / YouTube",
    module: "Calendario",
    date: "v2.5.1",
    icon: "History",
    title: "Límites dinámicos en el calendario",
    description: "La navegación del calendario ahora se mantiene entre el primer directo registrado y el mes o año actual. El acceso se desbloquea con suscripción activa en Twitch o membresía de YouTube, además de roles administrativos.",
    href: "/rastreador/calendario",
    cta: "Ver calendario",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "tracker.calendar.view",
  },
  {
    type: "Nuevo",
    audience: "Twitch / YouTube",
    module: "Rastreador",
    date: "v2.5.0",
    icon: "History",
    title: "Calendario histórico de directos",
    description: "El Archivo VOD suma un calendario mensual y anual para ver visualmente qué días tuvieron directos. Se desbloquea con suscripción activa en Twitch o membresía de YouTube, además de roles administrativos.",
    href: "/rastreador/calendario",
    cta: "Ver calendario",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "tracker.calendar.view",
  },
  {
    type: "Mejora",
    audience: "Todos",
    module: "Rastreador",
    date: "v2.4.2",
    icon: "Download",
    title: "Ayuda para descargar resubidos",
    description: "El detalle de cada resubido suma opciones guiadas para usar Cobalt o Streamlink cuando el player de OK.RU no carga.",
    href: "/rastreador",
    cta: "Ver rastreador",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.4.0",
    icon: "Compass",
    title: "Menú lateral en árbol",
    description: "La navegación agrupa Archivo VOD, Biblioteca de anime, Lecturas y Administración en nodos desplegables para ocupar menos espacio.",
    href: "/inicio",
    cta: "Ver navegación",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Rastreador",
    date: "v2.4.0",
    icon: "History",
    title: "Nuevos modos de vista",
    description: "El rastreador y la biblioteca de anime incorporan vistas Cómodo, Compacto y Tabla para elegir entre cards visuales y listados densos.",
    href: "/rastreador",
    cta: "Probar vistas",
  },
  {
    type: "Mejora",
    audience: "Usuarios",
    module: "Anime",
    date: "v2.4.0",
    icon: "Star",
    title: "Cards compactas de anime",
    description: "El modo compacto de anime ahora muestra poster, progreso, nota destacada, favoritos, nota personal y acceso a resubidos en menos espacio.",
    href: "/biblioteca-anime/viendo",
    cta: "Ver anime",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.3.0",
    icon: "Sparkles",
    title: "Novedades y guía de uso",
    description: "Nueva página para entender qué puedes hacer como invitado, usuario registrado, comunidad Twitch/YouTube o perfil administrativo.",
    href: "/novedades",
    cta: "Ver guía",
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Plataforma",
    date: "v2.3.0",
    icon: "History",
    title: "Historial de cambios completo",
    description: "El changelog ahora vive en su propia página, con filtros por texto, módulo y tipo para revisar toda la evolución de la plataforma.",
    href: "/changelog",
    cta: "Ver historial",
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Anime",
    date: "v2.2",
    icon: "Star",
    title: "Chulopuntos para calificar anime",
    description: "Las páginas Viendo y Terminados ahora permiten puntuar anime con notas decimales y mostrar la nota destacada por Kala.",
    href: "/biblioteca-anime/viendo",
    cta: "Ver anime",
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Rastreador",
    date: "v2.2",
    icon: "BookmarkCheck",
    title: "Mi lista de directos",
    description: "Guarda directos, marca vistos y separa lo pendiente de lo ya revisado desde una página personal.",
    href: "/mi-lista",
    cta: "Ver mi lista",
    authOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Anime",
    date: "v2.2",
    icon: "BookOpenCheck",
    title: "Mi lista anime",
    description: "Centraliza favoritos, viendo, terminados y pendientes para llevar tu seguimiento personal de anime.",
    href: "/mi-lista/anime",
    cta: "Ver lista anime",
    authOnly: true,
  },
  {
    type: "Mejora",
    audience: "Twitch / YouTube",
    module: "SpaceDrum",
    date: "v2.2",
    icon: "BookOpenCheck",
    title: "Lector bilingüe con progreso",
    description: "SpaceDrum permite leer capítulos en español e inglés, guardar progreso y continuar lectura. Por ahora se desbloquea con suscripción activa en Twitch o membresía de YouTube, además de roles administrativos.",
    href: "/spacedrum",
    cta: "Leer SpaceDrum",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "spacedrum.view",
  },
  {
    type: "Nuevo",
    audience: "Usuarios",
    module: "Perfil",
    date: "v2.1",
    icon: "UserRoundCog",
    title: "Perfil configurable",
    description: "Los usuarios pueden actualizar alias, email, avatar local y contraseña desde Configurar perfil.",
    href: "/perfil",
    cta: "Configurar perfil",
    authOnly: true,
  },
  {
    type: "Mejora",
    audience: "Admin",
    module: "Administración",
    date: "v2.1",
    icon: "History",
    title: "Historial administrativo",
    description: "Los mantenedores registran quién hizo cada acción, cuándo, sobre qué módulo y con snapshots de cambios.",
    href: "/administracion/roles",
    cta: "Ver administración",
    adminOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Admin",
    module: "Administración",
    date: "v2.1",
    icon: "ShieldCheck",
    title: "Mantenedores y permisos",
    description: "Usuarios, roles, rastreador, tags, anime y SpaceDrum se administran desde módulos separados y auditables.",
    href: "/administracion/usuarios",
    cta: "Ver mantenedores",
    adminOnly: true,
  },
  {
    type: "Nuevo",
    audience: "Todos",
    module: "Login",
    date: "v2.0",
    icon: "LogIn",
    title: "Login manual y Twitch",
    description: "La plataforma permite usuarios manuales, registro local y conexión con Twitch para sincronizar roles.",
    href: "/perfil",
    cta: "Configurar perfil",
    authOnly: true,
    loginLabel: "Iniciar sesión",
  },
];

export const newsGuideTutorials = [
  {
    module: "Calendario de directos",
    href: "/rastreador/calendario",
    cta: "Abrir calendario",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "tracker.calendar.view",
    steps: ["Cambia entre vista mensual y anual.", "Usa la leyenda para interpretar colores por estado.", "Selecciona un día para ver los directos archivados."],
  },
  {
    module: "Rastreador",
    href: "/rastreador",
    cta: "Abrir rastreador",
    steps: ["Busca por título, tag o descripción.", "Filtra por año, mes, estado y tags.", "Abre la ficha para ver resubidos."],
  },
  {
    module: "Mi lista",
    href: "/mi-lista",
    cta: "Ver mi lista",
    authOnly: true,
    steps: ["Guarda directos desde el rastreador.", "Separa guardados, por ver y vistos.", "Continúa desde tu lista personal."],
  },
  {
    module: "Biblioteca de anime",
    href: "/biblioteca-anime/viendo",
    cta: "Abrir biblioteca",
    steps: ["Marca Favorito, Quiero ver, Viendo o Terminado.", "Califica con chulopuntos si tu rol lo permite.", "Abre resubidos asociados."],
  },
  {
    module: "SpaceDrum",
    href: "/spacedrum",
    cta: "Leer SpaceDrum",
    loginLabel: "Activar acceso",
    lockedLabel: "Requiere beneficio activo",
    permissionCode: "spacedrum.view",
    steps: ["Activa una suscripción de Twitch o membresía de YouTube.", "Inicia sesión para sincronizar tu acceso.", "Selecciona idioma y continúa tu lectura."],
  },
  {
    module: "Perfil",
    href: "/perfil",
    cta: "Configurar perfil",
    authOnly: true,
    steps: ["Actualiza alias y email.", "Conecta Twitch o Google / YouTube como métodos de acceso.", "Sube avatar o configura contraseña cuando corresponda."],
  },
  {
    module: "Sugerencias/Reclamos",
    href: "/sugerencias-reclamos",
    cta: "Abrir soporte",
    authOnly: true,
    steps: ["Abre Sugerencias/Reclamos desde el menú de cuenta.", "Crea un ticket con tipo, asunto y mensaje.", "Revisa la respuesta desde la campana o desde tu bandeja."],
  },
  {
    module: "Administración",
    href: "/administracion/roles",
    cta: "Ir a administración",
    adminOnly: true,
    steps: ["Gestiona mantenedores según permisos.", "Configura roles por pantalla.", "Revisa historial y auditoría."],
  },
];

export const newsGuideHowTo = [
  {
    title: "Explorar el calendario",
    icon: "History",
    steps: ["Abre Calendario de directos.", "Elige año, mes o vista anual.", "Selecciona un día coloreado para ver sus directos."],
  },
  {
    title: "Opciones para descargar",
    icon: "Download",
    steps: ["Abre la ficha del resubido.", "Presiona Opciones para descargar.", "Usa Cobalt o Streamlink si OK.RU falla."],
  },
  {
    title: "Guardar un directo",
    icon: "BookmarkCheck",
    steps: ["Entra al rastreador.", "Presiona Guardar en el directo.", "Revísalo luego desde Mi lista."],
  },
  {
    title: "Marcar como visto",
    icon: "Check",
    steps: ["Busca el directo.", "Presiona Visto.", "Filtra tu lista para separar pendientes."],
  },
  {
    title: "Calificar un anime",
    icon: "Star",
    steps: ["Abre Viendo o Terminados.", "Presiona Puntuar o Tu nota.", "Guarda una nota entre 1 y 8."],
  },
  {
    title: "Continuar SpaceDrum",
    icon: "BookOpenCheck",
    steps: ["Activa una suscripción de Twitch o membresía de YouTube.", "Inicia sesión para sincronizar tu acceso.", "Presiona Continuar lectura para guardar el avance."],
  },
  {
    title: "Cambiar avatar",
    icon: "UserRoundCog",
    steps: ["Abre Configurar perfil.", "Arrastra o selecciona imagen.", "Guarda los cambios."],
  },
  {
    title: "Conectar cuentas externas",
    icon: "BadgeCheck",
    steps: ["Abre Login o Configurar perfil.", "Elige Twitch o YouTube.", "Autoriza para entrar con cualquiera de esos métodos."],
  },
  {
    title: "Enviar una sugerencia o reclamo",
    icon: "MessageCircle",
    steps: ["Abre Sugerencias/Reclamos desde tu cuenta.", "Presiona Nuevo ticket y completa asunto y mensaje.", "Sigue la respuesta desde la campana o el chat del ticket."],
  },
];

export const newsGuideComparison = [
  { feature: "Ver archivo y resubidos", guest: true, registered: true },
  { feature: "Login con Twitch o YouTube", guest: false, registered: true },
  { feature: "Calendario de directos", guest: false, registered: "Con acceso" },
  { feature: "Guardar directos", guest: false, registered: true },
  { feature: "Marcar visto", guest: false, registered: true },
  { feature: "Mi lista", guest: false, registered: true },
  { feature: "Mi lista anime", guest: false, registered: true },
  { feature: "Progreso SpaceDrum", guest: false, registered: "Con acceso" },
  { feature: "Perfil y avatar", guest: false, registered: true },
  { feature: "Sugerencias/Reclamos", guest: false, registered: true },
  { feature: "Calificar anime", guest: false, registered: true },
  { feature: "Beneficios por rol", guest: false, registered: "Según rol" },
];

export const newsGuideChangelog = [
  {
    version: "v2.12.0",
    date: "22 jul 2026",
    title: "Sincronización XLSX y protección de datos del Rastreador",
    type: "Nuevo",
    modules: ["Rastreador", "Administración", "Plataforma", "Autenticación"],
    changes: [
      "El mantenedor del Rastreador incorpora filtros para encontrar registros sin enlace OKRU, sin enlace Telegram y con enlaces duplicados dentro de un registro o compartidos entre varios directos.",
      "La exportación XLSX respeta la búsqueda, los filtros y el orden activos, incluye instrucciones de uso y protege ID_BD e ID_INTERNO como identificadores no editables.",
      "El mismo archivo exportado puede importarse para actualizar los campos editables de registros existentes mediante un modal de cuatro etapas: archivo, revisión, confirmación y resultado.",
      "Antes de confirmar se muestran las diferencias entre la base de datos y el Excel; identificadores alterados, filas repetidas, registros inexistentes, estados inválidos, archivos obsoletos y filas nuevas bloquean la operación.",
      "La actualización masiva se ejecuta de forma atómica, conserva auditoría administrativa y permite limpiar campos opcionales cuando la celda correspondiente se deja vacía.",
      "Se agregan los permisos tracker.export y tracker.import para controlar por rol las operaciones de descarga y actualización masiva.",
      "La creación de registros nuevos desde Excel queda diferida; en esta primera etapa la importación solo actualiza registros que ya existen.",
      "Las sesiones que quedaron inválidas después de restaurar una base de datos ahora se eliminan automáticamente para permitir un nuevo inicio de sesión sin borrar cookies manualmente.",
      "Los scripts de respaldo y restauración PostgreSQL detectan si la base corre mediante Docker Compose, un contenedor con nombre propio o una instalación disponible en el host.",
      "El respaldo de producción usa archivos parciales, valida el dump antes de publicarlo y bloquea el despliegue si no puede generar una copia utilizable.",
    ],
  },
  {
    version: "v2.11.2",
    date: "22 jul 2026",
    title: "Restauración de la automatización Twitch EventSub",
    type: "Corrección",
    modules: ["Rastreador", "Notificaciones", "Twitch"],
    changes: [
      "Se restablece el procesamiento automático de Twitch EventSub para volver a detectar el inicio de un directo.",
      "La detección vuelve a crear el card correspondiente en el Rastreador y a publicar la notificación de que Lolweapon está en directo.",
      "El registro manual reconoce una suscripción EventSub activa y evita crear duplicados en Twitch.",
    ],
  },
  {
    version: "v2.11.1",
    date: "20 jul 2026",
    title: "Reducción de carga en el estado público de Twitch",
    type: "Corrección",
    modules: ["Rastreador", "Plataforma", "Twitch"],
    changes: [
      "Se reduce la cantidad de consultas externas realizadas por /api/twitch/status mediante una caché compartida de corta duración.",
      "Las consultas simultáneas reutilizan una actualización en curso para evitar ráfagas de solicitudes contra Twitch y la base de datos.",
      "La detección periódica de beneficios y suscripciones conserva su funcionamiento y no depende de esta caché pública.",
    ],
  },
  {
    version: "v2.11.0",
    date: "17 jul 2026",
    title: "Sugerencias, reclamos y tickets",
    type: "Nuevo",
    modules: ["Soporte", "Administración", "Notificaciones", "Roles"],
    changes: [
      "Se incorpora /sugerencias-reclamos para que usuarios registrados creen tickets con tipo, asunto y mensaje desde el menú de cuenta.",
      "Cada ticket tiene una conversación tipo chat con respuestas del usuario y de administración, botón de volver contextual y soporte responsivo en móvil, tablet y escritorio.",
      "Las respuestas administrativas generan una notificación directa en la campana del usuario y el enlace abre la conversación correspondiente.",
      "Se agrega /administracion/tickets como mantenedor administrativo con estadísticas, búsqueda, filtros, tabla homologada, historial y acceso al detalle del ticket.",
      "Administración puede responder tickets, cambiar estado y conservar estados manuales finales sin que una respuesta posterior los sobrescriba indebidamente.",
      "Los tickets y conversaciones se actualizan en tiempo real mediante el canal WebSocket existente de notificaciones.",
      "Se agregan los modelos SupportTicket y SupportTicketMessage, sus APIs de usuario y administración, y la migración PostgreSQL correspondiente.",
      "Se agregan permisos support.tickets.view, support.tickets.create, admin.tickets.view y admin.tickets.update, ubicados según el orden del menú en el mantenedor de roles.",
      "El centro de notificaciones contempla respuestas de ticket como operación navegable hacia el chat.",
      "Se documenta el estándar visual de Tickets / Sugerencias-Reclamos y se actualiza la visión técnica del proyecto.",
    ],
  },
  {
    version: "v2.10.0",
    date: "13 jul 2026",
    title: "RTFM del archivo y mapa de accesos",
    type: "Nuevo",
    modules: ["RTFM", "Navegación", "Roles", "Acceso"],
    changes: [
      "Se agrega /rtfm como pantalla pública bajo Inicio para reunir el contexto del archivo, notas de uso, enlaces principales, fuentes comunitarias y playlists de OKRU.",
      "La pantalla RTFM incorpora un mapa de navegación en árbol con rutas visibles, permisos y roles agrupados por Base, Comunidad, Staff y Especial.",
      "El mapa oculta administración y códigos internos a usuarios no administrativos, pero mantiene visible la lectura de roles que pueden acceder a cada pantalla.",
      "Se agrega una leyenda de siglas de rol para TW_Tier, TW_VIP, YT_Miembro, Público, Invitado y Streamer.",
      "Se informa el rol del usuario actual dentro del mapa para identificar rápidamente qué accesos le corresponden.",
      "Se documenta que TW_VIP y YT_Miembro no se pueden obtener ni entregar beneficios adicionales hasta autorización de Kala.",
      "La sección RTFM se ajusta para móvil, tablet y escritorio con botones a ancho correcto, roles más legibles y superficies más sólidas para reducir fatiga visual.",
      "Se agrega el permiso rtfm.view y se asigna por defecto a los roles predefinidos junto con Novedades e Historial de cambios.",
      "SpaceDrum deja de mostrar 404 cuando un usuario conectado no tiene permiso y redirige a una pantalla explícita de acceso restringido.",
      "Login y Registro pasan a tratarse como pantallas solo para usuarios sin sesión; si ya existe sesión activa, redirigen a Inicio.",
    ],
  },
  {
    version: "v2.9.1",
    date: "12 jul 2026",
    title: "Ajustes de perfil y comunicación",
    type: "Mejora",
    modules: ["Perfil", "Novedades"],
    changes: [
      "Se ajusta el perfil para usar el menú lateral completo de la plataforma, evitando configuraciones separadas entre /inicio y /perfil.",
      "Se aclara en perfil, registro OAuth y novedades que los beneficios automáticos solo consideran suscripciones pagadas de Twitch; los roles TW_VIP y YT_Miembro no se pueden obtener ni entregar beneficios adicionales hasta que Kala autorice su activación.",
    ],
  },
  {
    version: "v2.9.0",
    date: "11 jul 2026",
    title: "Google / YouTube como método de acceso",
    type: "Nuevo",
    modules: ["Perfil", "Plataforma", "Administración"],
    changes: [
      "Se agrega inicio de sesión y registro con Google / YouTube usando OpenID Connect, con email verificado desde el proveedor.",
      "Las cuentas ahora pueden tener varios métodos de acceso conectados: usuario y contraseña, Twitch y Google / YouTube.",
      "El registro conectado reutiliza el formulario manual con datos precargados, email bloqueado y contraseña opcional para no obligar a crear una clave si se entra con proveedor externo.",
      "Cuando un proveedor usa el mismo correo que una cuenta existente, la vinculación exige reautenticarse con cualquiera de los métodos actuales de esa cuenta antes de conectar el nuevo proveedor.",
      "El perfil muestra los métodos conectados, permite conectar o desconectar proveedores y bloquea dejar una cuenta sin ningún método de acceso.",
      "Twitch mantiene la sincronización automática de roles por Tier, VIP o moderador; Google / YouTube registra usuarios nuevos con rol Público por defecto.",
      "Por ahora, los beneficios automáticos de la web solo consideran suscripciones pagadas de Twitch. Los roles TW_VIP y YT_Miembro no se pueden obtener ni entregar beneficios adicionales hasta que Kala autorice su activación (ja!).",
      "La pantalla de login informa claramente si una vinculación pendiente debe confirmarse con contraseña, Twitch, Google / YouTube o más de una alternativa disponible.",
      "Se corrigen cookies temporales de OAuth para que registros, vinculaciones abandonadas y logins posteriores no bloqueen cuentas válidas.",
      "El diseño de login, registro y perfil se ajusta para reducir mareo visual en tema oscuro, con superficies más sólidas, mejor contraste y menos capas translúcidas.",
      "Se documentan las variables de entorno, callbacks, reglas de rol, manejo de cuentas conectadas y convenciones visuales para futuras pantallas.",
    ],
  },
  {
    version: "v2.8.0",
    date: "3 jul 2026",
    title: "Centro y administración de notificaciones",
    type: "Nuevo",
    modules: ["Plataforma", "Administración", "Perfil", "Rastreador"],
    changes: [
      "Se incorpora /notificaciones como bandeja completa con búsqueda, filtros, paginación y operaciones para marcar, descartar y restaurar avisos.",
      "La campana y la pantalla Ver todas usan permisos independientes; los invitados reciben únicamente avisos públicos y conservan su estado localmente.",
      "Se agrega el mantenedor administrativo de notificaciones con creación, edición, audiencia, iconos, severidad, publicación inmediata o programada, expiración y eliminación lógica.",
      "El mantenedor sigue el estándar de administración con estadísticas, filtros, ordenamiento real, tabla con scroll interno, paginación, historial, confirmaciones y operaciones accesibles.",
      "Las publicaciones programadas se activan desde el servidor y las actualizaciones llegan en tiempo real por WebSocket, con sincronización de YouTube y deduplicación de avisos de contenido.",
      "La experiencia móvil de notificaciones usa cards compactas con acciones distribuidas según el espacio disponible y el mini player se limita a tablet y escritorio.",
      "Los formularios y modales del Rastreador se homologan con el calendario estándar, cierre explícito y variante compacta controlada por permisos.",
      "El registro de EventSub detecta suscripciones activas para evitar duplicados y comunica correctamente cuando la configuración ya existe.",
      "La sesión puede compartirse entre Resubidos y Viendo mediante cookies aisladas por ambiente, tanto para Twitch como para usuarios manuales.",
      "El último login se registra al crear cualquier sesión y una migración recupera fechas históricas cuando existe evidencia en PlatformSession.",
    ],
  },
  {
    version: "v2.7.0",
    date: "28 jun 2026",
    title: "Notificaciones manuales de resubidos",
    type: "Nuevo",
    modules: ["Rastreador", "Plataforma", "Administración"],
    changes: [
      "Se incorpora la acción Notificar resubido en el Rastreador público para roles con el permiso tracker.lives.notify.",
      "El mantenedor administrativo del Rastreador incorpora su propia acción mediante admin.lives.notify, una columna con la fecha del último aviso y confirmación explícita para reenviar.",
      "Cada aviso crea una notificación pública en tiempo real con enlace directo a la ficha del resubido, visible para usuarios autenticados e invitados.",
      "La creación de la notificación y la actualización de Live.notifiedAt se ejecutan en una única transacción PostgreSQL, con protección frente a dobles envíos concurrentes.",
      "Los envíos quedan registrados en el historial administrativo del Rastreador sin impedir la operación si la auditoría no está disponible.",
      "Se agregan permisos configurables separados para el Rastreador público y su mantenedor, manteniendo Notificar fuera de Mi lista.",
      "Las acciones de las cards se homologan en Rastreador, Mi lista e Inicio con iconos diferenciados para ficha, links y resubido, además de ajustes responsivos en móvil, tablet y vista tabla.",
      "Se corrige la separación entre Disponibilidad y Acciones en la tabla pública y la visibilidad completa de acciones en la tabla administrativa.",
      "Las APIs distinguen sesión ausente de permiso insuficiente y el flujo incorpora cobertura Playwright para permisos, confirmaciones y layouts responsivos.",
    ],
  },
  {
    version: "v2.6.2",
    date: "23 jun 2026",
    title: "Mejoras en el mini player de Twitch",
    type: "Mejora",
    modules: ["Plataforma"],
    changes: [
      "El mini player flotante ya no aparece en /inicio cuando el stream está activo.",
      "Se restaura el player de Twitch integrado en la sección de stream de la página principal.",
      "El player persistente se detiene automáticamente al entrar a /inicio para evitar doble audio con el player de home.",
      "El redimensionado del mini player aplica estilos directamente al DOM durante el drag, eliminando el desfase por ciclos de render de React.",
      "Se suprime la transición CSS de ancho y alto durante el redimensionado para mantener los botones cerrar y home alineados con el frame en todo momento.",
      "El botón home del mini player hace scroll al tope de la página al navegar a /inicio.",
    ],
  },
  {
    version: "v2.6.1",
    date: "23 jun 2026",
    title: "Correcciones del centro de notificaciones",
    type: "Corrección",
    modules: ["Plataforma", "Rastreador"],
    changes: [
      "Twitch EventSub queda correctamente habilitado para emitir notificaciones de directos en vivo.",
      "Las novedades y el historial de cambios se sincronizan con clave de deduplicación para evitar notificaciones duplicadas al reiniciar el servidor.",
      "El mini player de Twitch se muestra correctamente al navegar a /novedades y /changelog con el stream activo.",
      "Se mejora la recuperación del player tras pausas inesperadas al interactuar con el centro de notificaciones.",
      "Se corrige la ocultación del player en pantallas móviles al abrir el centro de notificaciones.",
    ],
  },
  {
    version: "v2.6.0",
    date: "22 jun 2026",
    title: "Centro de notificaciones en tiempo real",
    type: "Nuevo",
    modules: ["Plataforma"],
    changes: [
      "Se suma la campana de notificaciones en la barra superior, visible para usuarios autenticados e invitados.",
      "Las alertas incluyen directos en vivo detectados por Twitch EventSub, nuevos videos de YouTube y novedades de la plataforma.",
      "Los usuarios invitados ven notificaciones con audiencia pública; el estado leído y descartado se persiste en localStorage.",
      "Los usuarios autenticados almacenan su estado de lectura en base de datos mediante el modelo PlatformUserNotification.",
      "Las notificaciones se actualizan en tiempo real vía WebSocket con reconexión automática si la conexión se interrumpe.",
      "Las novedades y el historial de cambios se sincronizan una sola vez al iniciar el servidor usando dedupeKey para evitar duplicados.",
      "Se corrige la visibilidad del menú hamburguesa en mobile después del ajuste de z-index del topbar introducido en versiones anteriores.",
    ],
  },
  {
    version: "v2.5.2",
    date: "21 jun 2026",
    title: "Pulido visual de estados y acciones",
    type: "Corrección",
    modules: ["Rastreador", "Anime", "Plataforma"],
    changes: [
      "Los estados personales del rastreador quedan concentrados en los botones Guardar y Visto, evitando badges duplicados en las cards.",
      "El botón Visto usa un estado visual verde propio en cards y detalle para diferenciarlo mejor de Guardado.",
      "Los botones Ver y Ver resubidos de la biblioteca de anime incorporan icono de reproducción y ajustes de ancho para evitar cortes en vistas compactas.",
      "El scroll infinito del rastreador vuelve a observar el sentinel al navegar internamente desde otra pantalla, evitando que Cargando más resultados quede sin cargar contenido.",
      "Se documenta el patrón de `IntersectionObserver` en vistas condicionales para prevenir regresiones similares.",
    ],
  },
  {
    version: "v2.5.1",
    date: "21 jun 2026",
    title: "Límites dinámicos del calendario",
    type: "Mejora",
    modules: ["Rastreador"],
    changes: [
      "La navegación mensual del calendario queda limitada entre el primer mes con directos registrados y el mes actual.",
      "La vista anual queda limitada entre el primer año con directos registrados y el año actual.",
      "Los selectores de año y mes respetan el mismo rango para evitar periodos fuera del archivo.",
    ],
  },
  {
    version: "v2.5.0",
    date: "21 jun 2026",
    title: "Calendario histórico y estándares de mantenedores",
    type: "Nuevo",
    modules: ["Rastreador", "Administración", "Plataforma"],
    changes: [
      "El Archivo VOD suma un calendario histórico de directos con vista mensual y anual, navegación por periodo, botón Hoy y acceso directo por URL.",
      "El calendario de directos queda reservado a usuarios con suscripción activa en Twitch o membresía de YouTube, además de roles administrativos.",
      "Los días del calendario usan la misma paleta de estados del rastreador, con leyenda visible y tratamiento especial para días con estados mixtos.",
      "En mobile, al seleccionar un día en vista anual, la pantalla desplaza automáticamente al panel con los directos del día.",
      "Los estados del rastreador quedan homologados en cards, tabla, detalle, mantenedor y calendario mediante una fuente común de estilos.",
      "Los mantenedores administrativos se alinean al estándar visual: columnas atómicas, filtros compatibles, paginación no nativa, ordenamiento claro y scroll horizontal controlado.",
      "Se documenta el flujo de preplanificación, estándares de mantenedores, pruebas responsive y variables locales para Playwright autenticado.",
    ],
  },
  {
    version: "v2.4.2",
    date: "16 jun 2026",
    title: "Opciones de descarga para resubidos",
    type: "Mejora",
    modules: ["Rastreador"],
    changes: [
      "El detalle de resubido incorpora un modal de opciones para descargar cuando el player de OK.RU falla.",
      "El método recomendado copia el link de OK.RU y abre Cobalt para que el usuario intente descargar desde su navegador.",
      "El método avanzado con Streamlink mantiene instrucciones detalladas por sistema operativo, comando listo para copiar y ayuda de problemas comunes.",
      "La descarga no pasa por el servidor de la plataforma y no agrega integración API ni costos de proxy.",
    ],
  },
  {
    version: "v2.4.1",
    date: "15 jun 2026",
    title: "Corrección al crear card desde Twitch",
    type: "Corrección",
    modules: ["Rastreador", "Administración"],
    changes: [
      "Crear card desde Twitch ahora actualiza el listado del rastreador inmediatamente sin requerir recargar la página.",
      "El flujo de archivo desde Twitch usa actualización puntual del directo y evita depender de un refresco adicional para mostrar la card.",
    ],
  },
  {
    version: "v2.4.0",
    date: "15 jun 2026",
    title: "Menú árbol y modos compactos",
    type: "Mejora",
    modules: ["Plataforma", "Rastreador", "Anime"],
    changes: [
      "El menú lateral ahora usa una estructura en árbol con nodos desplegables para Archivo VOD, Biblioteca de anime, Lecturas y Administración.",
      "Administración organiza sus secciones internas con subárboles para Biblioteca de anime y SpaceDrum.",
      "El selector de densidad suma la vista Tabla y conserva Cómodo y Compacto para rastreador y biblioteca de anime.",
      "El modo compacto del rastreador usa cards densas con fecha, estado, tags resumidos, disponibilidad y acciones personales.",
      "El modo compacto de anime incorpora cards con poster, progreso, nota destacada, favoritos, nota personal y acceso al resubido.",
      "La vista Tabla queda disponible en pantallas medianas y grandes, con fallback automático a Compacto en mobile.",
      "Pulido visual del menú árbol: padres más sobrios, hijo activo destacado, línea guía e indicadores desplegables más claros.",
    ],
  },
  {
    version: "v2.3.0",
    date: "13 jun 2026",
    title: "Novedades y changelog",
    changes: [
      "Nueva página Novedades con beneficios por tipo de usuario, guías rápidas y accesos según sesión o permisos.",
      "Nueva página Historial de cambios con filtros por texto, módulo y tipo de cambio.",
      "Permisos configurables news.view y changelog.view, asignados por defecto a los roles predefinidos.",
      "El login, registro y Twitch conservan la página de retorno, incluso cuando se navega desde enlaces con ancla.",
      "Los selectores del changelog usan el componente visual estandarizado de la plataforma.",
    ],
  },
  {
    version: "v2.2.1",
    date: "02 jun 2026",
    title: "Ajustes de autenticación y estabilidad",
    changes: [
      "El login manual actualiza correctamente el último acceso del usuario.",
      "Correcciones finales sobre miniaturas y experiencia de SpaceDrum.",
    ],
  },
  {
    version: "v2.2.0",
    date: "30 may 2026",
    title: "SpaceDrum por rol y administración editorial",
    changes: [
      "Página de SpaceDrum con acceso por rol, selector de capítulos, lector, progreso por usuario e idioma.",
      "Mantenedores administrativos para capítulos, páginas, configuración e importación de SpaceDrum.",
      "Importación remota desde la web original, conservando progreso de usuarios registrados.",
      "Submenú administrativo para dividir capítulos, páginas, configuración e importación.",
      "Mejoras responsivas en tablas, acciones de anime y modo de lectura.",
      "Pulido visual de cards, hero, créditos, apoyo al proyecto y lector.",
    ],
  },
  {
    version: "v2.1.1",
    date: "24 may 2026",
    title: "Documentación y auditoría pulida",
    changes: [
      "Documentación del flujo manual de Git, versionado y releases.",
      "Corrección del desborde visual en el modal de historial administrativo.",
    ],
  },
  {
    version: "v2.1.0",
    date: "24 may 2026",
    title: "Chulopuntos, auditoría y mejoras del dashboard",
    changes: [
      "Sistema de chulopuntos con notas personales de 1 a 8 y soporte decimal.",
      "Nota destacada por Kala visible en cards de Viendo y Terminados.",
      "Historial administrativo con usuario, fecha, módulo, registro e instantáneas de cambios.",
      "Mejoras de experiencia en Inicio, player Twitch y convenciones internas del proyecto.",
      "Documentación del proyecto, backlog y guías compartidas para agentes.",
    ],
  },
  {
    version: "v2.0.0",
    date: "17 may 2026",
    title: "Actividad personal, CI/CD y estados de carga",
    changes: [
      "Seguimiento personal de actividad para guardar y marcar contenidos.",
      "Mi lista de directos con estados personales y navegación dedicada.",
      "Mejoras de UX, estados de carga y comportamiento del dashboard.",
      "Workflows de despliegue con respaldos, rollback y generación de Prisma.",
      "Mejor tolerancia ante cambios de navegación y carga inicial.",
    ],
  },
  {
    version: "v1.9.2",
    date: "15 may 2026",
    title: "Formulario compacto de anime",
    changes: [
      "Simplificación del formulario compacto de Biblioteca de anime.",
      "Campos acotados para edición rápida desde Viendo y Terminados.",
    ],
  },
  {
    version: "v1.9.1",
    date: "15 may 2026",
    title: "Acceso Twitch para usuarios nuevos",
    changes: [
      "Corrección para permitir el inicio de sesión de nuevos usuarios Twitch.",
      "Mejor manejo del alta inicial cuando la cuenta todavía no existe en plataforma.",
    ],
  },
  {
    version: "v1.9.0",
    date: "15 may 2026",
    title: "Mantenedores y permisos de plataforma",
    changes: [
      "Mantenedores administrativos para módulos principales de la plataforma.",
      "Permisos configurables por pantalla y acción desde Roles.",
      "Base para administrar usuarios, roles, rastreador, tags y anime con una línea visual común.",
      "Panel administrativo de tags con categorías, reglas, asignación manual y eliminación segura.",
      "Estandarización de tablas con filtros, paginación, ordenamiento, IDs y estados.",
    ],
  },
  {
    version: "v1.8.0",
    date: "14 may 2026",
    title: "Mantenedores de Biblioteca de anime",
    changes: [
      "Administración de anime Viendo y Terminados desde el módulo de administración.",
      "Operaciones internas para estado, eliminación y edición según permisos.",
      "Homologación de tablas, modales, filtros y acciones con Usuarios y Roles.",
      "Búsqueda y precarga desde AniList para crear o editar fichas.",
      "Formularios completo y compacto según permisos del rol.",
    ],
  },
  {
    version: "v1.7.3",
    date: "12 may 2026",
    title: "Entrada de invitados corregida",
    changes: [
      "Cambio del acceso invitado para mostrar Iniciar sesión de forma más clara.",
    ],
  },
  {
    version: "v1.7.2",
    date: "12 may 2026",
    title: "OAuth Twitch multi-host",
    changes: [
      "Soporte para iniciar sesión con Twitch desde distintos hosts configurados.",
      "Corrección del flujo QA/producción cuando se navega desde dominios separados.",
    ],
  },
  {
    version: "v1.7.1",
    date: "12 may 2026",
    title: "Redirección Twitch configurable",
    changes: [
      "Uso del origen configurado para evitar redirecciones erróneas a localhost.",
    ],
  },
  {
    version: "v1.7.0",
    date: "12 may 2026",
    title: "Autenticación, usuarios y roles",
    changes: [
      "Login manual, registro local y login con Twitch.",
      "Módulo de usuarios con restricciones especiales para Dios.",
      "Módulo de roles con permisos configurables por pantalla y acción.",
      "Perfil configurable con alias, email, avatar y cambio de contraseña.",
      "Roles temporales de comunidad, Twitch, YouTube, Público e Invitado.",
      "Reglas de acceso para pantallas públicas y administrativas según permisos.",
    ],
  },
  {
    version: "v1.6.0",
    date: "06 may 2026",
    title: "Persistencia normalizada en Postgres",
    changes: [
      "Migración desde datos JSON hacia modelo normalizado en PostgreSQL.",
      "Importadores y exportadores para directos, anime, tags y configuraciones.",
      "Base para operar local, QA y producción con Prisma y Postgres.",
      "Scripts para resetear secuencias y mantener IDs lógicos en ambientes limpios.",
      "Documentación operativa para migración, backups y restauración.",
    ],
  },
  {
    version: "v1.5.0",
    date: "01 may 2026",
    title: "Biblioteca de anime consolidada",
    changes: [
      "Reemplazo de la vista antigua de Viendo por la Biblioteca de anime.",
      "Sincronización de edición de fichas entre vistas públicas y administrativas iniciales.",
      "Mejoras de mini player y comportamiento del layout general.",
    ],
  },
  {
    version: "v1.4.1",
    date: "01 may 2026",
    title: "Orden y metadata de anime",
    changes: [
      "Mejoras en ordenamiento y presentación de la biblioteca.",
      "Conservación de metadata editada manualmente.",
    ],
  },
  {
    version: "v1.4.0",
    date: "01 may 2026",
    title: "Seguimiento de anime mejorado",
    changes: [
      "Mejoras en fichas de anime y seguimiento de episodios.",
      "Priorización de temporadas completas y capítulos comprados.",
      "Ajustes de títulos y metadata desde AniList.",
      "Cruce entre tags del rastreador y fichas de biblioteca.",
    ],
  },
  {
    version: "v1.3.1",
    date: "01 may 2026",
    title: "Corrección visual del menú anime",
    changes: [
      "Corrección del icono de Biblioteca de anime en el menú.",
    ],
  },
  {
    version: "v1.3.0",
    date: "01 may 2026",
    title: "Biblioteca de anime",
    changes: [
      "Alta del módulo Biblioteca de anime.",
      "Vistas para animes en seguimiento y terminados.",
      "Gestión inicial de fichas conectadas al rastreador y AniList.",
      "Primeras mejoras de orden, filtros y presentación de cards de anime.",
    ],
  },
  {
    version: "v1.2.5",
    date: "29 abr 2026",
    title: "Player Twitch estabilizado",
    changes: [
      "Estabilización de la ubicación del player Twitch en Inicio.",
    ],
  },
  {
    version: "v1.2.4",
    date: "29 abr 2026",
    title: "Tabla de rastreador y controles",
    changes: [
      "Mejoras en la tabla del rastreador.",
      "Controles más claros para abrir resubidos.",
    ],
  },
  {
    version: "v1.2.3",
    date: "28 abr 2026",
    title: "Mini player persistente",
    changes: [
      "Player Twitch persistente al cambiar entre páginas del rastreador.",
      "Menos parpadeos en embeds durante navegación interna.",
    ],
  },
  {
    version: "v1.2.2",
    date: "28 abr 2026",
    title: "Ayuda de descarga con Streamlink",
    changes: [
      "Guía auxiliar para descargar directos con Streamlink.",
    ],
  },
  {
    version: "v1.2.1",
    date: "28 abr 2026",
    title: "Links sociales en sidebar",
    changes: [
      "Accesos sociales movidos al menú lateral.",
      "Branding y favicon incorporados.",
    ],
  },
  {
    version: "v1.2.0",
    date: "27 abr 2026",
    title: "Página de detalle de resubido",
    changes: [
      "Nueva página para ver un resubido con player, metadata, tags y enlaces.",
      "Correcciones de carga al entrar al rastreador desde otras vistas.",
      "Primeras mejoras de embeds Twitch y acciones del archivo.",
      "Prototipo inicial de SpaceDrum dentro de la navegación.",
      "Categorías globales de tags para organizar el rastreador.",
    ],
  },
  {
    version: "v1.1.0",
    date: "26 abr 2026",
    title: "Hub multi-página",
    changes: [
      "Estructura multi-página para Inicio, Twitch y vistas internas.",
      "Primer prototipo de navegación integrada en la plataforma.",
    ],
  },
  {
    version: "v1.0.0",
    date: "19 abr 2026",
    title: "Base inicial en Next.js",
    changes: [
      "Migración inicial de la web de resubidos a Next.js full stack.",
      "Primera base del archivo VOD y navegación de la plataforma.",
    ],
  },
];
